repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: local
  hooks:
    - id: prompt-metadata
      name: Update prompt template metadata
      entry: poetry run python scripts/update_prompt_metadata.py
      language: system
      files: ^llm_orchestrator/prompts/tasks/.*\.yaml$
      pass_filenames: true 