repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
    - id: check-json
    - id: debug-statements
    - id: check-case-conflict
    - id: check-docstring-first

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: '1.7.1'
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: ["--no-update"]

- repo: local
  hooks:
    - id: prompt-metadata
      name: Update prompt template metadata
      entry: poetry run python scripts/update_prompt_metadata.py
      language: system
      files: ^llm_orchestrator/prompts/tasks/.*\.yaml$
      pass_filenames: true
    - id: sync-version
      name: Sync version with git tag
      entry: python .pre-commit-hooks/sync_version.py
      language: system
      files: ^pyproject\.toml$
      pass_filenames: false
