[tool.poetry]
name = "llm-orchestrator"
version = "0.1.0"
description = "A system for orchestrating large-scale LLM tasks"
authors = ["Lucas Whipple"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.10.6"
pytest = "^8.3.4"
ruff = "^0.9.3"
litellm = "^1.59.8"
jsonschema = "^4.23.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
