# Default security configuration for LLMaestro

# Global security settings
require_api_key_encryption: true
allowed_api_domains:
  - api.openai.com
  - api.anthropic.com
  - api.cohere.ai
  - api.mistral.ai

# Provider-specific security policies
provider_policies:
  openai:
    require_encryption: true
    allowed_domains:
      - api.openai.com
    allowed_endpoints:
      - /v1/chat/completions
      - /v1/completions
      - /v1/embeddings
    max_token_limit: 32768
    require_ssl: true

  anthropic:
    require_encryption: true
    allowed_domains:
      - api.anthropic.com
    allowed_endpoints:
      - /v1/messages
      - /v1/complete
    max_token_limit: 200000
    require_ssl: true

  cohere:
    require_encryption: true
    allowed_domains:
      - api.cohere.ai
    allowed_endpoints:
      - /v1/generate
      - /v1/embed
    max_token_limit: 32768
    require_ssl: true

  mistral:
    require_encryption: true
    allowed_domains:
      - api.mistral.ai
    allowed_endpoints:
      - /v1/chat/completions
    max_token_limit: 32768
    require_ssl: true 