name: Generate JSON Schemas

on:
  push:
    branches:
      - main  # or your default branch name
    paths:
      - 'src/**/*.py'  # Only run when Python files in src are changed

jobs:
  generate-schemas:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install

    - name: Generate schemas
      run: |
        poetry run python scripts/generate_schemas.py

    - name: Check for changes
      id: git-check
      run: |
        git add schemas/
        git status --porcelain
        echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.git-check.outputs.changes > 0
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Auto-generate JSON schemas [skip ci]" -a
        git push
